### ISSUE TITLE
動きませんでした

### ISSUE THREAD

**Issue by wata909** [frogcat/flood#2]
いくつかのブラウザ上で、動きませんでしたので、お知らせします。
状況としては、「Click to Run」をクリックすると、一面が水色になり、そのまま止まってしまいます。

## 動いた場合
OS:Ubuntu 16.04 LTS
Browser: Firefox 76.0.1 (64bit)

OS:Windows10 Pro 1909 64bit
Browser: Firefox 76.0.1 (64bit)

OS:Windows10 Pro 1903 64bit
Browser: Firefox 76.0.1 (64bit)

OS:Windows10 Pro 64bit　（詳細バージョン不明）
Browser: Google Chrome 81.0.4044.138（Official Build） （64 ビット）

## 動かない場合
OS:Windows10 Pro 1909 64bit
Browser: MS Edge 83.0.478.37 (公式ビルド) (64 ビット)

OS:Windows10 Pro 1903 64bit
Browser: MS Edge 83.0.478.37 (公式ビルド) (64 ビット)

OS:Windows10 Pro 1903 64bit
Browser: Google Chrome 83.0.4103.61（Official Build）(64 ビット)

**Comment by frogcat** [comment]
![image](https://user-images.githubusercontent.com/12029629/82748372-45584480-9ddc-11ea-84c7-0dbb36a3d7a3.png)

以下の環境で問題の再現確認できました。
OS: Windows 10 Pro 1909 64bit
Browser : Google Chrome バージョン: 83.0.4103.61（Official Build） （64 ビット）

**Comment by frogcat** [comment]
![image](https://user-images.githubusercontent.com/12029629/82748492-3625c680-9ddd-11ea-8809-405105676d83.png)

以下の環境では問題は再現せず、動作している模様
OS: Mint Linux 19
Browser : Google Chrome バージョン: 83.0.4103.61（Official Build） （64 ビット）

**Comment by frogcat** [comment]
Google Chrome 83 も MS Edge 83 もコアの Blink は共通なはず、あと Linux の Chrome 83 で問題がないのでたとえばこのあたりを丹念に掘っていけば何か問題が見つかるかも
https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%20type%3Dfeature%20webgl%20windows&can=2

**Comment by frogcat** [comment]
とりあえず次の Chrome 84 での動作を見てから対策するかどうか考えます

**Comment by wata909** [comment]
ありがとうございます。アップデートがあったら、こちらでも確認してみます。

**Comment by frogcat** [comment]
![image](https://user-images.githubusercontent.com/12029629/84233696-c8440380-ab2d-11ea-8933-6a80fbd644a1.png)
Chrome のマイナーバージョンアップがあったので以下の環境で確認したところ、動作していました。
OS: Windows 10 Pro 1909 64bit (OS ビルド 18363.657)
Browser: Google Chrome 83.0.4103.97（Official Build） （64 ビット）

**Comment by wata909** [comment]
動作確認しました。ひとまずcloseしますね。
